# Generated by Django 3.2.6 on 2021-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0002_rename_person_personmodell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('matnr', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('maktx_1', models.CharField(max_length=40)),
                ('maktx_2', models.CharField(max_length=40)),
                ('lifnr', models.CharField(max_length=10)),
                ('aritkelbild', models.FileField(upload_to='upload')),
            ],
        ),
    ]
