# Generated by Django 3.2.6 on 2021-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog1', '0003_artikel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='aritkelbild',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
